### PR TITLE
RPC v1 implementation Complete \o/

### PR DESCRIPTION
**Pull request by oyeb**
- added squareSource commands and changed LDAC pins temporarily
- Fixed typo in ISR, also changed window size.
- added RPC implementation in Task.cpp
- added `TScale`, `VScale`, `DC offset`, `squareSource`, `constHoldTime` (for gen. Sou
- 2 constructors for gen. Source
- Tested rpc_loop.ino and all_waves.ino, other examples might be broken
- Upgraded the RPC GUI with new commands and help

### CODE REVIEW

**Comment by oyeb** [comment]
The constant hold time didn't work out as we discussed.
A lot of multiplications, branching is being done to protect from user-land mistakes. These can be removed for speed later.

**Comment by jonnew** [comment]
Awesome, looks very promising. One organizational thing to start with: lets move the python GUI to `src/cyclopsctrl` or something like that rather than the source files sitting in the `lib` directory. Further, you may want to make it into a complete package (not that hard). 

https://python-packaging.readthedocs.io/en/latest/

**Comment by jonnew** [comment]
As per our discussion on slack, this is good to merge once the directory structure has been "flattened" and the python code has been moved to a package in the `src` directory.

**Comment by oyeb** [comment]
@jonnew Could you test the TRIG functions? Look at `Board.h` line 146 and the docs to set the test up.

**Comment by jonnew** [comment]
Yes, I will have a look today.

**Pull request merged**
